function deriv_h_u2T = dif_u_p2T( v1,v2,w1,w2,u1,u2,u3,u4,mu1,mu2,rho1,rho2,alpha1,alpha2, adjoint_v_1,adjoint_v_2,adjoint_w_1,adjoint_w_2,p1,p2)

% Numerical derivative of Hamiltonian w.r.t. timing control u4 (patch 2 timing)

h = 1e-4;

u4_right = min(0.9, u4 + h);
u4_left  = max(0,   u4 - h);

x = [v1;
     v2;
     w1;
     w2];

F_right = yearly_map( ...
    x,...
    u3,u4_right,...
    u1,u2,...
    mu1,mu2,rho1,rho2,...
    alpha1,alpha2,p1,p2);

F_left = yearly_map( ...
    x,...
    u3,u4_left,...
    u1,u2,...
    mu1,mu2,rho1,rho2,...
    alpha1,alpha2,p1,p2);

v1_r = F_right(1);
v2_r = F_right(2);
w1_r = F_right(3);
w2_r = F_right(4);

v1_l = F_left(1);
v2_l = F_left(2);
w1_l = F_left(3);
w2_l = F_left(4);

H_right = 5*u1^2 + 30*u2^2 + u3^2 + u4_right^2 ...
        + w1^2 + w2^2 ...
        + adjoint_v_1*v1_r ...
        + adjoint_v_2*v2_r ...
        + adjoint_w_1*w1_r ...
        + adjoint_w_2*w2_r;

H_left = 5*u1^2 + 30*u2^2 + u3^2 + u4_left^2 ...
       + w1^2 + w2^2 ...
       + adjoint_v_1*v1_l ...
       + adjoint_v_2*v2_l ...
       + adjoint_w_1*w1_l ...
       + adjoint_w_2*w2_l;

du = u4_right - u4_left;
deriv_h_u2T = (H_right - H_left)/(du);

end




##function [deriv_h_u4] =dif_u_p2T(v1,v2,w1,w2,u1,u2,u3,u4,mu1,mu2,rho1,rho2,alpha1,alpha2,adjoint_v_1,adjoint_v_2,adjoint_w_1,adjoint_w_2,p1,p2)
##%in this section, I approximate the derivative of each of my function wrt that state (using 2-point difference method)
##
##h=0.0001; %step size
##u_right_4 = min(1, u4 + h);
##u_left_4 = max(0, u4 - h);
##[v_right_1,v_right_2,w_right_1,w_right_2]=yearly_map(v1,v2,w1,w2,u1,u2,u3,u_right_4,mu1,mu2,rho1, rho2,alpha1, alpha2,p1,p2);
##[v_left_1,v_left_2,w_left_1,w_left_2]=yearly_map(v1,v2,w1,w2,u1,u2,u3,u_left_4,mu1,mu2,rho1,rho2,alpha1,alpha2,p1,p2);
##
##%hamiltonian - (cost function only includes cost of spraying and timing)
##h_right = u_right_4^2 + u1^2 + u2^2+ u3^2 + w1^2 + w2^2 ...
##          + adjoint_v_1 * v_right_1 ...
##          + adjoint_v_2 * v_right_2 ...
##          + adjoint_w_1 * w_right_1 ...
##          + adjoint_w_2 * w_right_2;
##
##h_left  = u_left_4^2 + u1^2 + u2^2+ u3^2 + w1^2 + w2^2 ...
##          + adjoint_v_1 * v_left_1 ...
##          + adjoint_v_2 * v_left_2 ...
##          + adjoint_w_1 * w_left_1 ...
##          + adjoint_w_2 * w_left_2;
##
##%Difference using divided difference formula
##deriv_h_u4=(h_right-h_left)/(2*h);
