function deriv_h_u2 = dif_u_p2I( ...
    v1,v2,w1,w2,u1,u2,u3,u4,...
    mu1,mu2,rho1,rho2,alpha1,alpha2,...
    adjoint_v_1,adjoint_v_2,...
    adjoint_w_1,adjoint_w_2,p1,p2)

h = 1e-4;

% perturb u2
u2_right = min(0.9,u2 + h);
u2_left  = max(0,u2 - h);


x = [v1;
     v2;
     w1;
     w2];
% forward evaluation
F_right = yearly_map( ...
    x,...
    u3,u4,...
    u1,u2_right,...
    mu1,mu2,rho1,rho2,...
    alpha1,alpha2,p1,p2);

F_left = yearly_map( ...
    x,...
    u3,u4,...
    u1,u2_left,...
    mu1,mu2,rho1,rho2,...
    alpha1,alpha2,p1,p2);

v1_r = F_right(1); v2_r = F_right(2);
w1_r = F_right(3); w2_r = F_right(4);

v1_l = F_left(1); v2_l = F_left(2);
w1_l = F_left(3); w2_l = F_left(4);

% Hamiltonian (same structure as p1 version)
H_right = 5*u1^2 + 30*u2_right^2 + u3^2 + u4^2 ...
        + w1^2 + w2^2 ...
        + adjoint_v_1*v1_r ...
        + adjoint_v_2*v2_r ...
        + adjoint_w_1*w1_r ...
        + adjoint_w_2*w2_r;

H_left  = 5*u1^2 + 30*u2_left^2 + u3^2 + u4^2 ...
        + w1^2 + w2^2 ...
        + adjoint_v_1*v1_l ...
        + adjoint_v_2*v2_l ...
        + adjoint_w_1*w1_l ...
        + adjoint_w_2*w2_l;

du = u2_right - u2_left;

deriv_h_u2 = (H_right - H_left)/(du);

end








##function [deriv_h_u2] =dif_u_p2I(v1,v2,w1,w2,u1,u2,u3,u4,mu1,mu2,rho1,rho2,alpha1,alpha2,adjoint_v_1,adjoint_v_2,adjoint_w_1,adjoint_w_2,p1,p2)
##%In this section, I approximate the derivative of each of my function wrt that state (using 2-point difference method)
##
##%control intensity patch 2
##h=0.0001; %step size
##u_right_2 = min(1, u2 + h);
##u_left_2 = max(0, u2 - h);
##[v_right_1,v_right_2,w_right_1,w_right_2]=yearly_map(v1,v2,w1,w2,u1,u_right_2,u3,u4,mu1,mu2,rho1, rho2,alpha1,alpha2,p1,p2);
##[v_left_1,v_left_2,w_left_1,w_left_2]=yearly_map(v1,v2,w1,w2,u1,u_left_2,u3,u4,mu1,mu2,rho1,rho2,alpha1,alpha2,p1,p2);
##
##%hamiltonian - (cost function only includes cost of spraying and timing)
##h_right = u_right_2^2 + u1^2 + u3^2 + u4^2 + w1^2 + w2^2 ...
##          + adjoint_v_1 * v_right_1 ...
##          + adjoint_v_2 * v_right_2 ...
##          + adjoint_w_1 * w_right_1 ...
##          + adjoint_w_2 * w_right_2;
##
##h_left  = u_left_2^2 + u1^2 + u3^2 + u4^2 + w1^2 + w2^2 ...
##          + adjoint_v_1 * v_left_1 ...
##          + adjoint_v_2 * v_left_2 ...
##          + adjoint_w_1 * w_left_1 ...
##          + adjoint_w_2 * w_left_2;
##
##%Difference using divided difference formula
##deriv_h_u2=(h_right-h_left)/(2*h);
